// Sample course data with expanded details
export const coursesTableData = [
  {
    id: "1",
    name: "Advanced Diploma in Accounting and Finance (ACCA route)",
    awardingBody: "BPP University",
    fees: "£8,010.00 full fees",
    color: "blue",
    details: {
      courseSubject: "ACCA",
      academicCredit: "330",
      qualification: "Advanced Diploma",
      awardingBody: "BPP University",
      recognition: "ACCA",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "18 months (full time)",
      fees: "£8,010 full fees",
      intakes: "September, March",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "2",
    name: "ACCA Professional Level Papers",
    awardingBody: "BPP University",
    fees: "£7,500.00 full fees",
    color: "green",
    details: {
      courseSubject: "ACCA",
      academicCredit: "360",
      qualification: "Professional Level",
      awardingBody: "BPP University",
      recognition: "ACCA",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "24 months (full time)",
      fees: "£7,500 full fees",
      intakes: "January, September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "3",
    name: "BSc (Hons) Accounting and Finance",
    awardingBody: "BPP University",
    fees: "£9,000.00 per year",
    color: "yellow",
    details: {
      courseSubject: "Accounting and Finance",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "BPP University",
      recognition: "Various professional bodies",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,000 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "4",
    name: "MBA in Financial Management",
    awardingBody: "BPP University",
    fees: "£12,500.00 full fees",
    color: "purple",
    details: {
      courseSubject: "Financial Management",
      academicCredit: "180",
      qualification: "MBA",
      awardingBody: "BPP University",
      recognition: "AMBA",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£12,500 full fees",
      intakes: "September, January",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "5",
    name: "Certificate in Financial Services",
    awardingBody: "London Institute of Banking",
    fees: "£3,200.00 full fees",
    color: "red",
    details: {
      courseSubject: "Financial Services",
      academicCredit: "60",
      qualification: "Certificate",
      awardingBody: "London Institute of Banking",
      recognition: "Industry recognised",
      academicLevel: "Level 3",
      studyMode: "Full Time",
      duration: "6 months (full time)",
      fees: "£3,200 full fees",
      intakes: "September, March",
      workPlacement: "No",
      location: "London",
    },
  },
];
