// Sample course data with expanded details
export const coursesTableData = [
  {
    id: "1",
    name: "Advanced Diploma in Accounting and Finance (ACCA route)",
    awardingBody: "BPP University",
    fees: "£8,010.00 full fees",
    color: "blue",
    details: {
      courseSubject: "ACCA",
      academicCredit: "330",
      qualification: "Advanced Diploma",
      awardingBody: "BPP University",
      recognition: "ACCA",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "18 months (full time)",
      fees: "£8,010 full fees",
      intakes: "September, March",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "2",
    name: "ACCA Professional Level Papers",
    awardingBody: "BPP University",
    fees: "£7,500.00 full fees",
    color: "green",
    details: {
      courseSubject: "ACCA",
      academicCredit: "360",
      qualification: "Professional Level",
      awardingBody: "BPP University",
      recognition: "ACCA",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "24 months (full time)",
      fees: "£7,500 full fees",
      intakes: "January, September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "3",
    name: "BSc (Hons) Accounting and Finance",
    awardingBody: "BPP University",
    fees: "£9,000.00 per year",
    color: "yellow",
    details: {
      courseSubject: "Accounting and Finance",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "BPP University",
      recognition: "Various professional bodies",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,000 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "4",
    name: "MBA in Financial Management",
    awardingBody: "BPP University",
    fees: "£12,500.00 full fees",
    color: "purple",
    details: {
      courseSubject: "Financial Management",
      academicCredit: "180",
      qualification: "MBA",
      awardingBody: "BPP University",
      recognition: "AMBA",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£12,500 full fees",
      intakes: "September, January",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "5",
    name: "Certificate in Financial Services",
    awardingBody: "London Institute of Banking",
    fees: "£3,200.00 full fees",
    color: "red",
    details: {
      courseSubject: "Financial Services",
      academicCredit: "60",
      qualification: "Certificate",
      awardingBody: "London Institute of Banking",
      recognition: "Industry recognised",
      academicLevel: "Level 3",
      studyMode: "Full Time",
      duration: "6 months (full time)",
      fees: "£3,200 full fees",
      intakes: "September, March",
      workPlacement: "No",
      location: "London",
    },
  },
  // Additional 50 random entries
  {
    id: "6",
    name: "MSc Data Analytics for Finance",
    awardingBody: "Imperial College London",
    fees: "£18,500.00 full fees",
    color: "teal",
    details: {
      courseSubject: "Finance Analytics",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "Imperial College London",
      recognition: "CIMA",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£18,500 full fees",
      intakes: "September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "7",
    name: "Diploma in Investment Banking",
    awardingBody: "London School of Economics",
    fees: "£11,200.00 full fees",
    color: "indigo",
    details: {
      courseSubject: "Investment Banking",
      academicCredit: "120",
      qualification: "Diploma",
      awardingBody: "London School of Economics",
      recognition: "CFA Institute",
      academicLevel: "Level 5",
      studyMode: "Part Time",
      duration: "12 months (part time)",
      fees: "£11,200 full fees",
      intakes: "January, May",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "8",
    name: "Advanced Certificate in Corporate Finance",
    awardingBody: "Chartered Institute for Securities & Investment",
    fees: "£4,800.00 full fees",
    color: "orange",
    details: {
      courseSubject: "Corporate Finance",
      academicCredit: "60",
      qualification: "Advanced Certificate",
      awardingBody: "Chartered Institute for Securities & Investment",
      recognition: "CISI",
      academicLevel: "Level 4",
      studyMode: "Distance Learning",
      duration: "9 months (distance learning)",
      fees: "£4,800 full fees",
      intakes: "Rolling",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "9",
    name: "BA (Hons) Business Management with Finance",
    awardingBody: "University of Manchester",
    fees: "£9,250.00 per year",
    color: "pink",
    details: {
      courseSubject: "Business Management",
      academicCredit: "360",
      qualification: "BA (Hons)",
      awardingBody: "University of Manchester",
      recognition: "CMI",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "Manchester",
    },
  },
  {
    id: "10",
    name: "Professional Diploma in Banking & Finance",
    awardingBody: "London Institute of Banking",
    fees: "£6,700.00 full fees",
    color: "cyan",
    details: {
      courseSubject: "Banking & Finance",
      academicCredit: "120",
      qualification: "Professional Diploma",
      awardingBody: "London Institute of Banking",
      recognition: "Banking Association",
      academicLevel: "Level 5",
      studyMode: "Evening Classes",
      duration: "18 months (evening classes)",
      fees: "£6,700 full fees",
      intakes: "January, September",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "11",
    name: "Certificate in Financial Risk Management",
    awardingBody: "Risk Management Association",
    fees: "£5,200.00 full fees",
    color: "lime",
    details: {
      courseSubject: "Risk Management",
      academicCredit: "60",
      qualification: "Certificate",
      awardingBody: "Risk Management Association",
      recognition: "GARP",
      academicLevel: "Level 4",
      studyMode: "Blended Learning",
      duration: "8 months (blended learning)",
      fees: "£5,200 full fees",
      intakes: "March, October",
      workPlacement: "No",
      location: "Birmingham",
    },
  },
  {
    id: "12",
    name: "BSc (Hons) Financial Mathematics",
    awardingBody: "University College London",
    fees: "£9,250.00 per year",
    color: "violet",
    details: {
      courseSubject: "Financial Mathematics",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "University College London",
      recognition: "IMA",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Optional",
      location: "London",
    },
  },
  {
    id: "13",
    name: "Advanced Diploma in Wealth Management",
    awardingBody: "Chartered Institute for Securities & Investment",
    fees: "£7,800.00 full fees",
    color: "amber",
    details: {
      courseSubject: "Wealth Management",
      academicCredit: "120",
      qualification: "Advanced Diploma",
      awardingBody: "Chartered Institute for Securities & Investment",
      recognition: "CISI",
      academicLevel: "Level 6",
      studyMode: "Part Time",
      duration: "15 months (part time)",
      fees: "£7,800 full fees",
      intakes: "February, August",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "14",
    name: "MSc International Accounting",
    awardingBody: "University of Edinburgh",
    fees: "£14,800.00 full fees",
    color: "emerald",
    details: {
      courseSubject: "International Accounting",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "University of Edinburgh",
      recognition: "ICAS",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£14,800 full fees",
      intakes: "September",
      workPlacement: "No",
      location: "Edinburgh",
    },
  },
  {
    id: "15",
    name: "Foundation Degree in Financial Services",
    awardingBody: "Coventry University",
    fees: "£6,500.00 per year",
    color: "fuchsia",
    details: {
      courseSubject: "Financial Services",
      academicCredit: "240",
      qualification: "Foundation Degree",
      awardingBody: "Coventry University",
      recognition: "Industry recognised",
      academicLevel: "Level 5",
      studyMode: "Full Time",
      duration: "2 years (full time)",
      fees: "£6,500 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "Coventry",
    },
  },
  {
    id: "16",
    name: "Postgraduate Certificate in Financial Planning",
    awardingBody: "Chartered Insurance Institute",
    fees: "£6,900.00 full fees",
    color: "sky",
    details: {
      courseSubject: "Financial Planning",
      academicCredit: "60",
      qualification: "Postgraduate Certificate",
      awardingBody: "Chartered Insurance Institute",
      recognition: "CII",
      academicLevel: "Level 7",
      studyMode: "Online",
      duration: "6 months (online)",
      fees: "£6,900 full fees",
      intakes: "January, April, September",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "17",
    name: "HNC in Business (Finance)",
    awardingBody: "Pearson",
    fees: "£5,400.00 full fees",
    color: "rose",
    details: {
      courseSubject: "Business Finance",
      academicCredit: "120",
      qualification: "HNC",
      awardingBody: "Pearson",
      recognition: "Industry recognised",
      academicLevel: "Level 4",
      studyMode: "Full Time",
      duration: "1 year (full time)",
      fees: "£5,400 full fees",
      intakes: "September, February",
      workPlacement: "Optional",
      location: "Leeds",
    },
  },
  {
    id: "18",
    name: "Professional Certificate in Taxation",
    awardingBody: "Chartered Institute of Taxation",
    fees: "£4,350.00 full fees",
    color: "slate",
    details: {
      courseSubject: "Taxation",
      academicCredit: "60",
      qualification: "Professional Certificate",
      awardingBody: "Chartered Institute of Taxation",
      recognition: "CIOT",
      academicLevel: "Level 5",
      studyMode: "Part Time",
      duration: "9 months (part time)",
      fees: "£4,350 full fees",
      intakes: "April, October",
      workPlacement: "No",
      location: "Manchester",
    },
  },
  {
    id: "19",
    name: "MBA Finance and Investment",
    awardingBody: "University of Warwick",
    fees: "£27,500.00 full fees",
    color: "blue",
    details: {
      courseSubject: "Finance and Investment",
      academicCredit: "180",
      qualification: "MBA",
      awardingBody: "University of Warwick",
      recognition: "AMBA, EQUIS",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£27,500 full fees",
      intakes: "September",
      workPlacement: "Yes",
      location: "Coventry",
    },
  },
  {
    id: "20",
    name: "Certificate in Pension Trusteeship",
    awardingBody: "Pensions Management Institute",
    fees: "£3,800.00 full fees",
    color: "green",
    details: {
      courseSubject: "Pension Management",
      academicCredit: "60",
      qualification: "Certificate",
      awardingBody: "Pensions Management Institute",
      recognition: "PMI",
      academicLevel: "Level 4",
      studyMode: "Distance Learning",
      duration: "6 months (distance learning)",
      fees: "£3,800 full fees",
      intakes: "March, September",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "21",
    name: "BSc (Hons) Economics with Finance",
    awardingBody: "University of Bristol",
    fees: "£9,250.00 per year",
    color: "yellow",
    details: {
      courseSubject: "Economics with Finance",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "University of Bristol",
      recognition: "Various professional bodies",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Optional",
      location: "Bristol",
    },
  },
  {
    id: "22",
    name: "Diploma in Fund Administration",
    awardingBody: "Investment Association",
    fees: "£4,900.00 full fees",
    color: "purple",
    details: {
      courseSubject: "Fund Administration",
      academicCredit: "120",
      qualification: "Diploma",
      awardingBody: "Investment Association",
      recognition: "Industry recognised",
      academicLevel: "Level 4",
      studyMode: "Part Time",
      duration: "12 months (part time)",
      fees: "£4,900 full fees",
      intakes: "February, August",
      workPlacement: "No",
      location: "Edinburgh",
    },
  },
  {
    id: "23",
    name: "Advanced Diploma in Banking Operations",
    awardingBody: "London Institute of Banking",
    fees: "£7,200.00 full fees",
    color: "red",
    details: {
      courseSubject: "Banking Operations",
      academicCredit: "120",
      qualification: "Advanced Diploma",
      awardingBody: "London Institute of Banking",
      recognition: "Banking Association",
      academicLevel: "Level 5",
      studyMode: "Blended Learning",
      duration: "15 months (blended learning)",
      fees: "£7,200 full fees",
      intakes: "January, June",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "24",
    name: "MSc Financial Technology",
    awardingBody: "University of Strathclyde",
    fees: "£16,400.00 full fees",
    color: "teal",
    details: {
      courseSubject: "Financial Technology",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "University of Strathclyde",
      recognition: "FCA Tech Pioneers",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£16,400 full fees",
      intakes: "September",
      workPlacement: "Optional",
      location: "Glasgow",
    },
  },
  {
    id: "25",
    name: "Professional Diploma in Treasury Management",
    awardingBody: "Association of Corporate Treasurers",
    fees: "£8,600.00 full fees",
    color: "indigo",
    details: {
      courseSubject: "Treasury Management",
      academicCredit: "120",
      qualification: "Professional Diploma",
      awardingBody: "Association of Corporate Treasurers",
      recognition: "ACT",
      academicLevel: "Level 6",
      studyMode: "Distance Learning",
      duration: "18 months (distance learning)",
      fees: "£8,600 full fees",
      intakes: "April, October",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "26",
    name: "Certificate in Mortgage Advice & Practice",
    awardingBody: "London Institute of Banking",
    fees: "£1,950.00 full fees",
    color: "orange",
    details: {
      courseSubject: "Mortgage Advice",
      academicCredit: "45",
      qualification: "Certificate",
      awardingBody: "London Institute of Banking",
      recognition: "FCA approved",
      academicLevel: "Level 3",
      studyMode: "Online",
      duration: "4 months (online)",
      fees: "£1,950 full fees",
      intakes: "Rolling",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "27",
    name: "BSc (Hons) Banking and International Finance",
    awardingBody: "City, University of London",
    fees: "£9,250.00 per year",
    color: "pink",
    details: {
      courseSubject: "Banking and International Finance",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "City, University of London",
      recognition: "CFA Institute",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "London",
    },
  },
  {
    id: "28",
    name: "Postgraduate Diploma in Islamic Finance",
    awardingBody: "Durham University",
    fees: "£9,800.00 full fees",
    color: "cyan",
    details: {
      courseSubject: "Islamic Finance",
      academicCredit: "120",
      qualification: "Postgraduate Diploma",
      awardingBody: "Durham University",
      recognition: "AAOIFI",
      academicLevel: "Level 7",
      studyMode: "Part Time",
      duration: "12 months (part time)",
      fees: "£9,800 full fees",
      intakes: "January",
      workPlacement: "No",
      location: "Durham",
    },
  },
  {
    id: "29",
    name: "Foundation Certificate in Financial Services",
    awardingBody: "Chartered Institute for Securities & Investment",
    fees: "£2,400.00 full fees",
    color: "lime",
    details: {
      courseSubject: "Financial Services",
      academicCredit: "30",
      qualification: "Foundation Certificate",
      awardingBody: "Chartered Institute for Securities & Investment",
      recognition: "CISI",
      academicLevel: "Level 2",
      studyMode: "Evening Classes",
      duration: "4 months (evening classes)",
      fees: "£2,400 full fees",
      intakes: "February, May, September, November",
      workPlacement: "No",
      location: "Birmingham",
    },
  },
  {
    id: "30",
    name: "MSc Accounting and Financial Management",
    awardingBody: "Lancaster University",
    fees: "£13,750.00 full fees",
    color: "violet",
    details: {
      courseSubject: "Accounting and Financial Management",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "Lancaster University",
      recognition: "ACCA, CIMA, ICAEW",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£13,750 full fees",
      intakes: "September",
      workPlacement: "No",
      location: "Lancaster",
    },
  },
  {
    id: "31",
    name: "Advanced Certificate in Retirement Provision",
    awardingBody: "Pensions Management Institute",
    fees: "£3,950.00 full fees",
    color: "amber",
    details: {
      courseSubject: "Retirement Provision",
      academicCredit: "60",
      qualification: "Advanced Certificate",
      awardingBody: "Pensions Management Institute",
      recognition: "PMI",
      academicLevel: "Level 4",
      studyMode: "Distance Learning",
      duration: "8 months (distance learning)",
      fees: "£3,950 full fees",
      intakes: "March, September",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "32",
    name: "Higher Apprenticeship in Banking (Level 4)",
    awardingBody: "London Institute of Banking",
    fees: "Funded by employer",
    color: "emerald",
    details: {
      courseSubject: "Banking",
      academicCredit: "120",
      qualification: "Higher Apprenticeship",
      awardingBody: "London Institute of Banking",
      recognition: "Industry recognised",
      academicLevel: "Level 4",
      studyMode: "Work-based Learning",
      duration: "18-24 months (work-based)",
      fees: "Funded by employer",
      intakes: "January, September",
      workPlacement: "Yes",
      location: "Various",
    },
  },
  {
    id: "33",
    name: "BA (Hons) Finance, Accounting and Economics",
    awardingBody: "University of Essex",
    fees: "£9,250.00 per year",
    color: "fuchsia",
    details: {
      courseSubject: "Finance, Accounting and Economics",
      academicCredit: "360",
      qualification: "BA (Hons)",
      awardingBody: "University of Essex",
      recognition: "ACCA, CIMA",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Optional",
      location: "Colchester",
    },
  },
  {
    id: "34",
    name: "Professional Certificate in International Trade Finance",
    awardingBody: "London Institute of Banking",
    fees: "£5,100.00 full fees",
    color: "sky",
    details: {
      courseSubject: "International Trade Finance",
      academicCredit: "60",
      qualification: "Professional Certificate",
      awardingBody: "London Institute of Banking",
      recognition: "ICC",
      academicLevel: "Level 5",
      studyMode: "Online",
      duration: "9 months (online)",
      fees: "£5,100 full fees",
      intakes: "April, October",
      workPlacement: "No",
      location: "Online",
    },
  },
  {
    id: "35",
    name: "HND in Accounting",
    awardingBody: "Pearson",
    fees: "£6,000.00 per year",
    color: "rose",
    details: {
      courseSubject: "Accounting",
      academicCredit: "240",
      qualification: "HND",
      awardingBody: "Pearson",
      recognition: "Industry recognised",
      academicLevel: "Level 5",
      studyMode: "Full Time",
      duration: "2 years (full time)",
      fees: "£6,000 per year",
      intakes: "September",
      workPlacement: "Yes",
      location: "Newcastle",
    },
  },
  {
    id: "36",
    name: "MSc Investment and Wealth Management",
    awardingBody: "Imperial College London",
    fees: "£34,000.00 full fees",
    color: "slate",
    details: {
      courseSubject: "Investment and Wealth Management",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "Imperial College London",
      recognition: "CFA Institute",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£34,000 full fees",
      intakes: "September",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "37",
    name: "Diploma in Financial Crime Prevention",
    awardingBody: "International Compliance Association",
    fees: "£3,750.00 full fees",
    color: "blue",
    details: {
      courseSubject: "Financial Crime Prevention",
      academicCredit: "60",
      qualification: "Diploma",
      awardingBody: "International Compliance Association",
      recognition: "ICA",
      academicLevel: "Level 4",
      studyMode: "Blended Learning",
      duration: "6 months (blended learning)",
      fees: "£3,750 full fees",
      intakes: "January, April, September",
      workPlacement: "No",
      location: "Multiple",
    },
  },
  {
    id: "38",
    name: "BSc (Hons) Finance, Investment and Risk",
    awardingBody: "University of Kent",
    fees: "£9,250.00 per year",
    color: "green",
    details: {
      courseSubject: "Finance, Investment and Risk",
      academicCredit: "360",
      qualification: "BSc (Hons)",
      awardingBody: "University of Kent",
      recognition: "CISI, CFA Institute",
      academicLevel: "Level 6",
      studyMode: "Full Time",
      duration: "3 years (full time)",
      fees: "£9,250 per year",
      intakes: "September",
      workPlacement: "Optional",
      location: "Canterbury",
    },
  },
  {
    id: "39",
    name: "Certificate in Equity Capital Markets",
    awardingBody: "Chartered Institute for Securities & Investment",
    fees: "£3,400.00 full fees",
    color: "yellow",
    details: {
      courseSubject: "Equity Capital Markets",
      academicCredit: "45",
      qualification: "Certificate",
      awardingBody: "Chartered Institute for Securities & Investment",
      recognition: "CISI",
      academicLevel: "Level 3",
      studyMode: "Part Time",
      duration: "6 months (part time)",
      fees: "£3,400 full fees",
      intakes: "March, September",
      workPlacement: "No",
      location: "London",
    },
  },
  {
    id: "40",
    name: "MSc Banking and Digital Finance",
    awardingBody: "University of Stirling",
    fees: "£11,900.00 full fees",
    color: "purple",
    details: {
      courseSubject: "Banking and Digital Finance",
      academicCredit: "180",
      qualification: "MSc",
      awardingBody: "University of Stirling",
      recognition: "Chartered Banker Institute",
      academicLevel: "Level 7",
      studyMode: "Full Time",
      duration: "12 months (full time)",
      fees: "£11,900 full fees",
      intakes: "September",
      workPlacement: "No",
      location: "Stirling",
    },
  },
  {
    id: "41",
    name: "Advanced Diploma in Insurance",
    awardingBody: "Chartered Insurance Institute",
    fees: "£4,800.00 full fees",
    color: "red",
    details: {
      courseSubject: "Insurance",
      academicCredit: "120",
      qualification: "Advanced Diploma",
      awardingBody: "Chartered Insurance Institute",
      recognition: "CII",
      academicLevel: "Level 6",
      studyMode: "Distance Learning",
      duration: "24 months (distance learning)",
      fees: "£4,800 full fees",
      intakes: "Rolling",
      workPlacement: "No",
      location: "Online",
    },
  }
]